const colors = {
  light: {
    text: '#111827',
    tint: '#4F46E5',
    background: '#F9FAFB',
    foreground: '#111827',
    card: '#FFFFFF',
    cardForeground: '#111827',
    primary: '#4F46E5',
    primaryForeground: '#FFFFFF',
    secondary: '#F3F4F6',
    secondaryForeground: '#374151',
    muted: '#F3F4F6',
    mutedForeground: '#6B7280',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E5E7EB',
    input: '#E5E7EB',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    surface: '#FFFFFF',
    overlay: 'rgba(0,0,0,0.5)',
  },
  dark: {
    text: '#F9FAFB',
    tint: '#818CF8',
    background: '#0F1117',
    foreground: '#F9FAFB',
    card: '#1A1D27',
    cardForeground: '#F9FAFB',
    primary: '#6366F1',
    primaryForeground: '#FFFFFF',
    secondary: '#1E2030',
    secondaryForeground: '#D1D5DB',
    muted: '#1E2030',
    mutedForeground: '#9CA3AF',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#2D3148',
    input: '#2D3148',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    surface: '#1A1D27',
    overlay: 'rgba(0,0,0,0.7)',
  },
  radius: 12,
};

export default colors;
