import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  backBtn: { width: 36 },
  headerTitle: { fontSize: 18 },
  scroll: { padding: 16, paddingBottom: 32, gap: 24 },
  serviceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    gap: 14,
  },
  serviceIcon: { width: 48, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  serviceName: { fontSize: 17 },
  serviceMeta: { fontSize: 14, marginTop: 3 },
  section: { gap: 14 },
  sectionTitle: { fontSize: 17 },
  dateRow: { gap: 8 },
  dateBtn: {
    width: 64,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    gap: 2,
  },
  dateDayName: { fontSize: 11 },
  dateNum: { fontSize: 20 },
  dateMonth: { fontSize: 11 },
  footer: { padding: 16, borderTopWidth: 1 },
  confirmBtn: { paddingVertical: 16, borderRadius: 14, alignItems: 'center' },
  confirmText: { fontSize: 16 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    gap: 20,
  },
  modalHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center' },
  modalTitle: { fontSize: 22, textAlign: 'center' },
  modalInfo: { padding: 16, gap: 14 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  infoLabel: { fontSize: 14, width: 60 },
  infoValue: { fontSize: 15, flex: 1, textAlign: 'right' },
  modalBtns: { flexDirection: 'row', gap: 12 },
  modalCancelBtn: { flex: 1, paddingVertical: 15, borderRadius: 12, alignItems: 'center', borderWidth: 1 },
  modalCancelText: { fontSize: 16 },
  modalConfirmBtn: { flex: 1, paddingVertical: 15, borderRadius: 12, alignItems: 'center' },
  modalConfirmText: { color: '#fff', fontSize: 16 },
});