import { StyleSheet } from "react-native";
import { rs, normalize } from "@/lib/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: rs(16),
    paddingBottom: rs(14),
    borderBottomWidth: 1,
  },
  backBtn: { width: rs(36) },
  headerTitle: { fontSize: normalize(16) },
  scroll: { padding: rs(16), paddingBottom: rs(32), gap: rs(24) },
  serviceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: rs(16),
    borderRadius: rs(14),
    borderWidth: 1,
    gap: rs(14),
  },
  serviceIcon: { width: rs(48), height: rs(48), borderRadius: rs(12), alignItems: 'center', justifyContent: 'center' },
  serviceName: { fontSize: normalize(14) },
  serviceMeta: { fontSize: normalize(12), marginTop: rs(3) },
  section: { gap: rs(14) },
  sectionTitle: { fontSize: normalize(14) },
  dateRow: { gap: rs(8) },
  dateBtn: {
    width: rs(64),
    alignItems: 'center',
    paddingVertical: rs(12),
    borderRadius: rs(12),
    borderWidth: 1,
    gap: rs(2),
  },
  dateDayName: { fontSize: normalize(11) },
  dateNum: { fontSize: normalize(16) },
  dateMonth: { fontSize: normalize(11) },
  footer: { padding: rs(16), borderTopWidth: 1 },
  confirmBtn: { paddingVertical: rs(16), borderRadius: rs(14), alignItems: 'center' },
  confirmText: { fontSize: normalize(13) },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: {
    borderTopLeftRadius: rs(24),
    borderTopRightRadius: rs(24),
    padding: rs(24),
    gap: rs(20),
  },
  modalHandle: { width: rs(40), height: rs(4), borderRadius: rs(2), alignSelf: 'center' },
  modalTitle: { fontSize: normalize(22), textAlign: 'center' },
  modalInfo: { padding: rs(16), gap: rs(14) },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: rs(10) },
  infoLabel: { fontSize: normalize(14), width: rs(60) },
  infoValue: { fontSize: normalize(15), flex: 1, textAlign: 'right' },
  modalBtns: { flexDirection: 'row', gap: rs(12) },
  modalCancelBtn: { flex: 1, paddingVertical: rs(15), borderRadius: rs(12), alignItems: 'center', borderWidth: 1 },
  modalCancelText: { fontSize: normalize(16) },
  modalConfirmBtn: { flex: 1, paddingVertical: rs(15), borderRadius: rs(12), alignItems: 'center' },
  modalConfirmText: { color: '#fff', fontSize: normalize(16) },
});