import { StyleSheet } from "react-native";
import { rs, normalize } from "@/lib/responsive";

export const styles = StyleSheet.create({
  container: { paddingHorizontal: rs(20), gap: rs(20) },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  title: { fontSize: normalize(26) },
  ownerCard: { flexDirection: "row", alignItems: "center", gap: rs(14) },
  avatar: {
    width: rs(60),
    height: rs(60),
    borderRadius: rs(30),
    alignItems: "center",
    justifyContent: "center",
  },
  initials: { color: "#fff", fontSize: normalize(22) },
  ownerName: { fontSize: normalize(18) },
  ownerEmail: { fontSize: normalize(13), marginTop: rs(2) },
  roleBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: rs(10),
    paddingVertical: rs(4),
    borderRadius: rs(20),
    marginTop: rs(4),
  },
  roleText: { fontSize: normalize(12) },
  card: { borderRadius: rs(16), borderWidth: 1, padding: rs(18), gap: rs(16) },
  cardTitle: { fontSize: normalize(17) },
  field: { gap: rs(8) },
  label: { fontSize: normalize(14) },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: rs(10),
    paddingHorizontal: rs(12),
    paddingVertical: rs(12),
    gap: rs(10),
  },
  input: { flex: 1, fontSize: normalize(15) },
  catRow: { gap: rs(8) },
  catChip: {
    paddingHorizontal: rs(14),
    paddingVertical: rs(8),
    borderRadius: rs(20),
    borderWidth: 1,
  },
  catText: { fontSize: normalize(14) },
  textAreaWrap: { borderWidth: 1, borderRadius: rs(10), padding: rs(12) },
  textArea: { fontSize: normalize(15), minHeight: rs(80), textAlignVertical: "top" },
  saveBtn: {
    paddingVertical: rs(15),
    borderRadius: rs(12),
    alignItems: "center",
    marginTop: rs(4),
  },
  saveBtnText: { color: "#fff", fontSize: normalize(16) },
  langRow: { flexDirection: "row", gap: rs(10) },
  langBtn: {
    flex: 1,
    paddingVertical: rs(10),
    alignItems: "center",
    borderRadius: rs(10),
    borderWidth: 1,
  },
  langText: { fontSize: normalize(15) },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: rs(10),
    paddingVertical: rs(15),
    borderRadius: rs(14),
    borderWidth: 1,
  },
  signOutText: { fontSize: normalize(16) },
  imageUpload: {
    height: rs(120),
    borderRadius: rs(12),
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  uploadPlaceholder: { alignItems: "center", gap: rs(8) },
  uploadPlaceholderText: { fontSize: normalize(13) },
  uploadPreview: { width: "100%", height: "100%" },
  uploadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailBox: { padding: rs(12), borderRadius: rs(10), backgroundColor: 'rgba(0,0,0,0.02)', gap: rs(4) },
  detailLabel: { fontSize: normalize(12), opacity: 0.6, marginTop: rs(8) },
  detailText: { fontSize: normalize(15) },
});