import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  heroImage: { width: '100%', height: 260, resizeMode: 'cover' },
  heroPlaceholder: { width: '100%', height: 260, alignItems: 'center', justifyContent: 'center' },
  content: { padding: 20 },
  titleRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  businessName: { fontSize: 26, marginBottom: 8 },
  catBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20 },
  catText: { fontSize: 13 },
  section: { marginBottom: 24, gap: 12 },
  sectionTitle: { fontSize: 18 },
  bio: { fontSize: 15, lineHeight: 24 },
  emptyServices: { alignItems: 'center', gap: 8, paddingVertical: 24 },
  emptyText: { fontSize: 14 },
  backBtn: {
    position: 'absolute',
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  bookBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    borderTopWidth: 1,
    gap: 12,
  },
  bookBarLeft: { flex: 1, gap: 2 },
  bookBarService: { fontSize: 15 },
  bookBarPrice: { fontSize: 14 },
  bookBtn: { paddingHorizontal: 24, paddingVertical: 14, borderRadius: 12 },
  bookBtnText: { color: '#fff', fontSize: 16 },
});